spring.application.name=backend

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://db01/accounts
spring.datasource.username=admin
spring.datasource.password=admin123

minio.url=http://dockerminio:9000
minio.access.name=admin
minio.access.secret=admin123
minio.bucket.name=profile-image