apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-db
  namespace: k8s-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-db
  template:
    metadata:
      labels:
        app: k8s-db
    spec:
      containers:
        - name: k8s-db
          image: lynakiddy/k8s-db
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: db-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: db-password
            - name: POSTGRES_DB
              value: accounts
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
