apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-minio
  namespace: k8s-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-minio
  template:
    metadata:
      labels:
        app: k8s-minio
    spec:
      containers:
        - name: k8s-minio
          image: lynakiddy/k8s-minio
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: minio-name
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: minio-secret
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: minio-storage
              mountPath: /data
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: minio-pvc
