apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-ingress
  namespace: k8s-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: kubernetes.lynasovann.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: k8s-web
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: k8s-api
                port:
                  number: 8080
          - path: /minio
            pathType: Prefix
            backend:
              service:
                name: k8s-minio
                port:
                  number: 9000
