apiVersion: v1
kind: Secret
metadata:
  name: k8s-secret
  namespace: k8s-dev
data:
  db-username: YWRtaW4K # admin
  db-password: YWRtaW4xMjMK # admin123
  minio-name: YWRtaW4K # admin
  minio-secret: YWRtaW4xMjMK # admin123
  minio-bucket: cHJvZmlsZS1pbWFnZQo= # profile-image
