apiVersion: v1
kind: Secret
metadata:
  name: k8s-secret
  namespace: k8s-dev
data:
  db-username: YWRtaW4= # admin
  db-password: YWRtaW4xMjM= # admin123
  minio-name: YWRtaW4= # admin
  minio-secret: YWRtaW4xMjM= # admin123
  minio-bucket: cHJvZmlsZS1pbWFnZQ== # profile-image
